cognitive_v:
  value: null
crossover_rate:
  value: null
inertia_v:
  value: null
max_eval:
  value: null
max_gen:
  value: null
mutation_rate:
  value: null
pop_size:
  value: null
social_v:
  value: null
